spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  #数据库连接配置信息
  datasource:
    #    url: jdbc:mysql://47.98.39.45:9097/oa1114?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.0.103:3306/mx?useUnicode=true&characterEncoding=UTF-8
#    #    url: jdbc:mysql://192.168.123.6:3306/oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#    url: jdbc:mysql://116.62.220.91:4389/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    username: jxoa
#    password: 'jxoa-18!**;'

server:
  port: 8080
staticPath:  D:/static/common/
