spring:
  datasource:
    url: jdbc:mysql://47.110.39.144:9306/mx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 'jxoa-2019_mt_oa'
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000

#      redis配置信息
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 10


staticPath: /data/wwwroot/img/
#staticPath:  D:/static/common/
server:
  port: 8080

