spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

server:
  port: 8080
staticPath:  D:/static/common/

